Vagrant.configure("2") do |config|
  config.vm.box = "chef/ubuntu-14.04"
  config.vm.network "forwarded_port", guest: 8080, host: 18080
  config.vm.network "forwarded_port", guest: 80, host:19080
  config.vm.network "forwarded_port", guest: 9990, host:19990 


  config.vm.provider "virtualbox" do |v|
    v.memory = 3092
    v.cpus = 2
  end
  

 config.vm.provision "docker" do |d|
    
    d.build_image "--tag=wildfly /vagrant/wildfly"
    d.run "wildfly", args: "-p 8080:8080 -p 9990:9990"

  end

end